version: '3.7'

services:
  vimo-server:
    image: vimo-server
    networks:
      - vimo-net
    ports:
      - 4242:4242
    environment:
      - ALLOW_ORIGINS=["*"]
      - VIMO_LOGGING=off
      - PORT=4242
networks:
  vimo-net:
